/**
 * Copyright (c) 2023 Raspberry Pi (Trading) Ltd. for temp_sensor example code
 * This project was based on the temp_sensor example downloaded via the VSCode Raspberry Pi Pico Project Extension
 * The revised code in server_common includes modifications generated by Google Code Assist
 * with further modifications/tweaks done by C Gerrish (Gerrikoio) (c) May 2025
 * Google Code Assist also added in its own comments
 * 
 * This file contains the BLE functions required to handle read, writes and updates
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#include <stdbool.h>
#include <stdio.h>
#include "btstack.h"
#include "hardware/adc.h"

#include "6dof_sensor.h"
#include "server_common.h"

#define APP_AD_FLAGS 0x06
static uint8_t adv_data[] = {
    // Flags general discoverable
    0x02, BLUETOOTH_DATA_TYPE_FLAGS, APP_AD_FLAGS,
    // Name
    0x05, BLUETOOTH_DATA_TYPE_COMPLETE_LOCAL_NAME, 'P', 'i', 'c', 'o',
    0x03, BLUETOOTH_DATA_TYPE_COMPLETE_LIST_OF_16_BIT_SERVICE_CLASS_UUIDS, 0x18,0x1A,
    0x11, BLUETOOTH_DATA_TYPE_COMPLETE_LIST_OF_128_BIT_SERVICE_CLASS_UUIDS,0x14,0x12,0x8A,0x76,0x04,0xD1,0x6C,0x4F,0x7E,0x53,0xF2,0xE8,0x10,0x00,0xB1,0x19,

};

static const uint8_t adv_data_len = sizeof(adv_data);

static const uint8_t *DESCR_SAMPLE_RATE = "Sample Rate (Hz)";
static const uint8_t *DESCR_PITCH = "Pitch Angle";
static const uint8_t *DESCR_ROLL = "Roll Angle";
static const uint8_t *DESCR_HEADING_RAW = "Heading: Raw";
static const uint8_t *DESCR_HEADING_COMP = "Heading: Compensated"; // This line is context from your previous changes
hci_con_handle_t con_handle = HCI_CON_HANDLE_INVALID;


notification_status_t g_notification_status;
data_ready_status_t g_data_ready_status;

uint16_t current_temp;
uint16_t sample_rate;
uint32_t pitch_deg; // Renamed from tilt_deg
uint32_t roll_deg;
uint32_t heading_deg_raw;
uint32_t heading_deg_comp;



void packet_handler(uint8_t packet_type, uint16_t channel, uint8_t *packet, uint16_t size) {
    UNUSED(size);
    UNUSED(channel);
    bd_addr_t local_addr;
    if (packet_type != HCI_EVENT_PACKET) return;

    uint8_t event_type = hci_event_packet_get_type(packet);
    switch(event_type){
        case BTSTACK_EVENT_STATE:
            if (btstack_event_state_get_state(packet) != HCI_STATE_WORKING) return;
            gap_local_bd_addr(local_addr);
            printf("BTstack up and running on %s.\r\n", bd_addr_to_str(local_addr));

            // setup advertisements
            uint16_t adv_int_min = 800;
            uint16_t adv_int_max = 800;
            uint8_t adv_type = 0;
            bd_addr_t null_addr;
            memset(null_addr, 0, 6);
            gap_advertisements_set_params(adv_int_min, adv_int_max, adv_type, 0, null_addr, 0x07, 0x00);
            assert(adv_data_len <= 31); // ble limitation
            gap_advertisements_set_data(adv_data_len, (uint8_t*) adv_data);
            gap_advertisements_enable(1);

            //poll_temp();
            break;

        case HCI_EVENT_LE_META:
            if (hci_event_le_meta_get_subevent_code(packet) == HCI_SUBEVENT_LE_CONNECTION_COMPLETE){
                uint8_t status = hci_subevent_le_connection_complete_get_status(packet);
                if (status == 0) { // Successfully connected
                    uint16_t new_connection_handle = hci_subevent_le_connection_complete_get_connection_handle(packet);
                    // Only print if we were previously not connected
                    if (con_handle == HCI_CON_HANDLE_INVALID) {
                        printf("Central device connected. Handle: 0x%04X\r\n", new_connection_handle);
                    }
                    con_handle = new_connection_handle; // Update our state to the new valid handle
                }
                // If status != 0, connection failed. We don't print "connected" and con_handle isn't updated.
            }
            break;
        case HCI_EVENT_DISCONNECTION_COMPLETE:
            // Only process if we previously thought we were connected.
            if (con_handle != HCI_CON_HANDLE_INVALID) {
                uint16_t disconnected_handle = hci_event_disconnection_complete_get_connection_handle(packet);
                // It's good practice to ensure the disconnect event is for the handle we are tracking,
                // though for a single-connection peripheral, con_handle should match disconnected_handle.
                printf("Central device disconnected. Handle: 0x%04X\r\n", disconnected_handle);
                con_handle = HCI_CON_HANDLE_INVALID; // Update our state
                memset(&g_notification_status, 0, sizeof(notification_status_t)); // Reset notification flags
                memset(&g_data_ready_status, 0, sizeof(data_ready_status_t));
            }
            break;
        case ATT_EVENT_CAN_SEND_NOW:
            if (g_notification_status.temperature && g_data_ready_status.temperature) {
                att_server_notify(con_handle, ATT_CHARACTERISTIC_ORG_BLUETOOTH_CHARACTERISTIC_TEMPERATURE_01_VALUE_HANDLE, (uint8_t*)&current_temp, sizeof(current_temp));
                g_data_ready_status.temperature = false;
            }
            
            if (g_notification_status.pitch && g_data_ready_status.pitch) {
                att_server_notify(con_handle, ATT_CHARACTERISTIC_19B10013_E8F2_537E_4F6C_D104768A1214_01_VALUE_HANDLE, (uint8_t*)&pitch_deg, sizeof(pitch_deg));
                g_data_ready_status.pitch = false;
            }
            if (g_notification_status.roll && g_data_ready_status.roll) {
                att_server_notify(con_handle, ATT_CHARACTERISTIC_19B10014_E8F2_537E_4F6C_D104768A1214_01_VALUE_HANDLE, (uint8_t*)&roll_deg, sizeof(roll_deg));
                g_data_ready_status.roll = false;
            }
            if (g_notification_status.heading_raw && g_data_ready_status.heading_raw) {
                att_server_notify(con_handle, ATT_CHARACTERISTIC_19B10015_E8F2_537E_4F6C_D104768A1214_01_VALUE_HANDLE, (uint8_t*)&heading_deg_raw, sizeof(heading_deg_raw));
                g_data_ready_status.heading_raw = false;
            }
            if (g_notification_status.heading_comp && g_data_ready_status.heading_comp) {
                att_server_notify(con_handle, ATT_CHARACTERISTIC_19B10016_E8F2_537E_4F6C_D104768A1214_01_VALUE_HANDLE, (uint8_t*)&heading_deg_comp, sizeof(heading_deg_comp));
                g_data_ready_status.heading_comp = false;
            }
            break;
        default:
            break;
    }
}

uint16_t att_read_callback(hci_con_handle_t connection_handle, uint16_t att_handle, uint16_t offset, uint8_t * buffer, uint16_t buffer_size) {
    UNUSED(connection_handle);

    switch (att_handle) {
        // enivonment service - temperature
        case ATT_CHARACTERISTIC_ORG_BLUETOOTH_CHARACTERISTIC_TEMPERATURE_01_VALUE_HANDLE:
            return att_read_callback_handle_blob((const uint8_t *)&current_temp, sizeof(current_temp), offset, buffer, buffer_size);
        // orientation custom service - sample rate
        case ATT_CHARACTERISTIC_19B10012_E8F2_537E_4F6C_D104768A1214_01_VALUE_HANDLE:
            return att_read_callback_handle_blob((const uint8_t *)&sample_rate, sizeof(sample_rate), offset, buffer, buffer_size);
        // orientation custom service - pitch
        case ATT_CHARACTERISTIC_19B10013_E8F2_537E_4F6C_D104768A1214_01_VALUE_HANDLE: // Pitch
            return att_read_callback_handle_blob((const uint8_t *)&pitch_deg, sizeof(pitch_deg), offset, buffer, buffer_size);
        // orientation custom service - roll
        case ATT_CHARACTERISTIC_19B10014_E8F2_537E_4F6C_D104768A1214_01_VALUE_HANDLE:
            return att_read_callback_handle_blob((const uint8_t *)&roll_deg, sizeof(roll_deg), offset, buffer, buffer_size);
        // orientation custom service - heading raw
        case ATT_CHARACTERISTIC_19B10015_E8F2_537E_4F6C_D104768A1214_01_VALUE_HANDLE:
            return att_read_callback_handle_blob((const uint8_t *)&heading_deg_raw, sizeof(heading_deg_raw), offset, buffer, buffer_size);
        // orientation custom service - heading compensated
        case ATT_CHARACTERISTIC_19B10016_E8F2_537E_4F6C_D104768A1214_01_VALUE_HANDLE:
            return att_read_callback_handle_blob((const uint8_t *)&heading_deg_comp, sizeof(heading_deg_comp), offset, buffer, buffer_size);
        
        // description handles for each custom characteristic
        case ATT_CHARACTERISTIC_19B10012_E8F2_537E_4F6C_D104768A1214_01_USER_DESCRIPTION_HANDLE:
            return att_read_callback_handle_blob((const uint8_t *)DESCR_SAMPLE_RATE, strlen(DESCR_SAMPLE_RATE), offset, buffer, buffer_size);
        case ATT_CHARACTERISTIC_19B10013_E8F2_537E_4F6C_D104768A1214_01_USER_DESCRIPTION_HANDLE:
            return att_read_callback_handle_blob((const uint8_t *)DESCR_PITCH, strlen(DESCR_PITCH), offset, buffer, buffer_size);
        case ATT_CHARACTERISTIC_19B10014_E8F2_537E_4F6C_D104768A1214_01_USER_DESCRIPTION_HANDLE:
            return att_read_callback_handle_blob((const uint8_t *)DESCR_ROLL, strlen(DESCR_ROLL), offset, buffer, buffer_size);
        case ATT_CHARACTERISTIC_19B10015_E8F2_537E_4F6C_D104768A1214_01_USER_DESCRIPTION_HANDLE:
            return att_read_callback_handle_blob((const uint8_t *)DESCR_HEADING_RAW, strlen(DESCR_HEADING_RAW), offset, buffer, buffer_size);
        case ATT_CHARACTERISTIC_19B10016_E8F2_537E_4F6C_D104768A1214_01_USER_DESCRIPTION_HANDLE:
            return att_read_callback_handle_blob((const uint8_t *)DESCR_HEADING_COMP, strlen(DESCR_HEADING_COMP), offset, buffer, buffer_size);
        default:
            return 0;
    }

}

int att_write_callback(hci_con_handle_t connection_handle, uint16_t att_handle, uint16_t transaction_mode, uint16_t offset, uint8_t *buffer, uint16_t buffer_size) {
    UNUSED(transaction_mode);
    UNUSED(offset);
    UNUSED(buffer_size);

    uint16_t cccd_value = little_endian_read_16(buffer, 0);
    bool notifications_enabled_for_char = (cccd_value == GATT_CLIENT_CHARACTERISTICS_CONFIGURATION_NOTIFICATION);
    bool request_can_send_now = false;

    switch (att_handle) {
        case ATT_CHARACTERISTIC_ORG_BLUETOOTH_CHARACTERISTIC_TEMPERATURE_01_CLIENT_CONFIGURATION_HANDLE:
            g_notification_status.temperature = notifications_enabled_for_char;
            if (g_notification_status.temperature) {
                g_data_ready_status.temperature = true; // Mark for initial send
                request_can_send_now = true;
            }
            printf("Temperature notifications: %s\r\n", g_notification_status.temperature ? "ON" : "OFF");
            break;

        case ATT_CHARACTERISTIC_19B10013_E8F2_537E_4F6C_D104768A1214_01_CLIENT_CONFIGURATION_HANDLE: // Pitch
            g_notification_status.pitch = notifications_enabled_for_char;
            if (g_notification_status.pitch) {
                g_data_ready_status.pitch = true; // Mark for initial send
                request_can_send_now = true;
            }
            printf("Pitch notifications: %s\r\n", g_notification_status.pitch ? "ON" : "OFF");
            break;

        case ATT_CHARACTERISTIC_19B10014_E8F2_537E_4F6C_D104768A1214_01_CLIENT_CONFIGURATION_HANDLE: // Roll
            g_notification_status.roll = notifications_enabled_for_char;
            if (g_notification_status.roll) {
                g_data_ready_status.roll = true; // Mark for initial send
                request_can_send_now = true;
            }
            printf("Roll notifications: %s\r\n", g_notification_status.roll ? "ON" : "OFF");
            break;

        case ATT_CHARACTERISTIC_19B10015_E8F2_537E_4F6C_D104768A1214_01_CLIENT_CONFIGURATION_HANDLE: // Heading Raw
            g_notification_status.heading_raw = notifications_enabled_for_char;
            if (g_notification_status.heading_raw) {
                g_data_ready_status.heading_raw = true; // Mark for initial send
                request_can_send_now = true;
            }
            printf("Heading Raw notifications: %s\r\n", g_notification_status.heading_raw ? "ON" : "OFF");
            break;

        case ATT_CHARACTERISTIC_19B10016_E8F2_537E_4F6C_D104768A1214_01_CLIENT_CONFIGURATION_HANDLE: // Heading Compensated
            g_notification_status.heading_comp = notifications_enabled_for_char;
            if (g_notification_status.heading_comp) {
                g_data_ready_status.heading_comp = true; // Mark for initial send
                request_can_send_now = true;
            }
            printf("Heading Comp notifications: %s\r\n", g_notification_status.heading_comp ? "ON" : "OFF");
            break;

        default:
            return 0; // Not a CCCD we are interested in
    }

    if (request_can_send_now) {
        con_handle = connection_handle; // Store the connection handle
        att_server_request_can_send_now_event(con_handle);
    }

    return 0;
}

void poll_temp(void) {
    adc_select_input(ADC_CHANNEL_TEMPSENSOR);
    uint32_t raw32 = adc_read();
    const uint32_t bits = 12;

    // Scale raw reading to 16 bit value using a Taylor expansion (for 8 <= bits <= 16)
    uint16_t raw16 = raw32 << (16 - bits) | raw32 >> (2 * bits - 16);

    // ref https://github.com/raspberrypi/pico-micropython-examples/blob/master/adc/temperature.py
    const float conversion_factor = 3.3 / (65535);
    float reading = raw16 * conversion_factor;
    
    // The temperature sensor measures the Vbe voltage of a biased bipolar diode, connected to the fifth ADC channel
    // Typically, Vbe = 0.706V at 27 degrees C, with a slope of -1.721mV (0.001721) per degree. 
    float deg_c = 27 - (reading - 0.706) / 0.001721;
    current_temp = deg_c * 100;

    printf("Temperature: %.2f degc\r\n", deg_c);
 }
